services:
  - type: web
    name: meme-wale-babu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT meme:app
    plan: free
    autoDeploy: true
